# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./GameObject.h \
    ./gamewindow.h \
    ./scene.h \
    ./bullet.h \
    ./target.h
SOURCES += ./GameObject.cpp \
    ./scene.cpp \
    ./gamewindow.cpp \
    ./main.cpp \
    ./bullet.cpp \
    ./target.cpp
FORMS += ./gamewindow.ui
RESOURCES += gamewindow.qrc
