# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------


TEMPLATE = app
TARGET = Small_Game
DESTDIR = ../x64/Debug
CONFIG += debug
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
HEADERS += ./player.h \
    ./myscene.h \
    ./coin.h
SOURCES += ./coin.cpp \
    ./main.cpp \
    ./myscene.cpp \
    ./player.cpp
RESOURCES += resources.qrc
