# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = tictactoe
DESTDIR = ../x64/Debug
CONFIG += debug
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
HEADERS += ./mainwindow.h \
    ./tictactoewidget.h \
    configurationdialog.h
SOURCES += ./mainwindow.cpp \
    ./main.cpp \
    ./tictactoewidget.cpp \
    configurationdialog.cpp
FORMS += ./mainwindow.ui \
    configurationdialog.ui
RESOURCES += mainwindow.qrc
